name: HologramX
version: '1.0.0'
main: com.hologramx.HologramX
api-version: '1.21'
authors: [YourName]
description: Advanced hologram plugin for Paper 1.21+ using display entities
website: https://github.com/yourname/HologramX
softdepend: [PlaceholderAPI]

commands:
  hologramx:
    description: Main HologramX command
    usage: /hologramx <subcommand>
    aliases: [hx]
    permission: hologramx.use
  hologram:
    description: User hologram command
    usage: /hologram <subcommand>
    aliases: [holo]
    permission: hologramx.user

permissions:
  hologramx.*:
    description: Access to all HologramX features
    default: op
    children:
      hologramx.admin: true
      hologramx.use: true
      hologramx.user: true
  hologramx.admin:
    description: Administrative access
    default: op
  hologramx.use:
    description: Basic command access
    default: op
  hologramx.user:
    description: User command access
    default: true
  hologramx.create:
    description: Create holograms
    default: op
  hologramx.delete:
    description: Delete holograms
    default: op
  hologramx.edit:
    description: Edit holograms
    default: op
  hologramx.move:
    description: Move holograms
    default: op
  hologramx.reload:
    description: Reload plugin
    default: op
  hologramx.interact.*:
    description: Interact with all holograms
    default: true
  hologramx.view.*:
    description: View all holograms
    default: true